# Generated by Django 4.2.1 on 2023-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_js', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker_details',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
