# Generated by Django 4.2.1 on 2023-10-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_js', '0002_job_seeker_details_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_seeker_details',
            old_name='intested_in',
            new_name='intrested_in',
        ),
        migrations.RenameField(
            model_name='job_seeker_details',
            old_name='Phone_number',
            new_name='mobile_number',
        ),
    ]
