# Generated by Django 4.2.7 on 2023-11-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_js', '0004_remove_job_seeker_details_intrested_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_apply_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email_id', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=40, null=True)),
                ('salary', models.CharField(blank=True, max_length=40, null=True)),
                ('resume', models.FileField(upload_to='static/resume/')),
                ('date_of_birth', models.CharField(blank=True, max_length=40, null=True)),
                ('about', models.CharField(blank=True, max_length=40, null=True)),
                ('heighest_qualification', models.CharField(blank=True, max_length=40, null=True)),
                ('skills', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
