# Generated by Django 4.2.7 on 2023-11-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_js', '0005_job_apply_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply_detail',
            name='resume',
            field=models.FileField(upload_to='../static/resume/'),
        ),
    ]
