# Generated by Django 4.2.7 on 2023-11-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_js', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_id2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
