# Generated by Django 4.2.7 on 2023-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_js', '0008_remove_customuser_username_customuser_email_id2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='job_seeker_details',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images/'),
        ),
        migrations.AddField(
            model_name='job_seeker_details',
            name='userid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
