# Generated by Django 4.2.1 on 2023-10-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_jg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_giver_details',
            name='Email_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='job_giver_details',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
