# Generated by Django 4.2.1 on 2023-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_jg', '0003_alter_job_giver_details_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_giver_details',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
