# Generated by Django 4.2.1 on 2023-10-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_giver_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('Email_id', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, max_length=40, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=40, null=True)),
                ('education', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
