# Generated by Django 4.2.1 on 2023-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_jg', '0002_alter_job_giver_details_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_giver_details',
            name='Email_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
