# Generated by Django 4.2.7 on 2023-11-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_jg', '0005_job_avl_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_giver_details',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images/'),
        ),
        migrations.AddField(
            model_name='job_giver_details',
            name='userid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
