# Generated by Django 4.2.7 on 2023-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_jg', '0006_job_giver_details_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_avl_detail',
            name='jobid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
